apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-script
  namespace: otus-hw6-anton
data:
  init.sql: |
    create schema auth;

    create table if not exists auth.Users(
        "Id" UUID primary key,
        "FirstName" character varying,
        "LastName" character varying,
        "Email" character varying,
        "Password" character varying,
        "Roles" character varying,
        CONSTRAINT EMAIL_UNIQUE UNIQUE ("Email"));

    GRANT TRIGGER, DELETE, SELECT, INSERT, TRUNCATE, UPDATE, REFERENCES ON TABLE auth.Users TO my_user;  

    create schema profile;

    create table if not exists profile.Profiles(
        "UserId" UUID primary key,
        "Age" int,
        "Sex" character varying,
        "AvatarUri" character varying);

    GRANT TRIGGER, DELETE, SELECT, INSERT, TRUNCATE, UPDATE, REFERENCES ON TABLE profile.Profile TO my_user;  