apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: otus-hw6-anton
data:
  init.sql: |
    create table if not exists public.my_users(
        "Id" UUID primary key,
        "FirstName" character varying,
        "LastName" character varying,
        "Email" character varying,
        "Password" character varying,
        "Roles" character varying);

    ALTER TABLE public.my_users ADD CONSTRAINT Email_UNIQUE UNIQUE ("Email");

    GRANT TRIGGER, DELETE, SELECT, INSERT, TRUNCATE, UPDATE, REFERENCES ON TABLE public.MY_USERS TO my_user;  