apiVersion: batch/v1
kind: Job
metadata:
  name: my-db-init-job
  namespace: otus-hw6-anton
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: postgres-init-table
          image: postgres:17.0
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: db-settings
                  key: DB_HOST
            - name: DBNAME
              valueFrom:
                configMapKeyRef:
                  name: db-settings
                  key: DB_NAME
          command: ["/bin/bash", "-c"]
          args:
            - psql -d "$DBNAME" -f /scripts/init.sql
          volumeMounts:
            - name: sql-script
              mountPath: /scripts
      containers:
        - name: postgres-init-siteadmin
          image: postgres:17.0
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: db-settings
                  key: DB_HOST
            - name: DBNAME
              valueFrom:
                configMapKeyRef:
                  name: db-settings
                  key: DB_NAME
            - name: SITE_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SITE_ADMIN_EMAIL
            - name: SITE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SITE_ADMIN_PASSWORD
          command: ["/bin/bash", "-c"]
          args:
            - psql -d "$DBNAME" -c "INSERT INTO public.my_users (\"Id\", \"Email\", \"Password\", \"Roles\") VALUES ('c218e91f-9d6c-4fee-aba5-a9e87766dc70', '$SITE_ADMIN_EMAIL', '$SITE_ADMIN_PASSWORD', 'admin')"          
      volumes:
        - name: sql-script
          configMap:
            name: db-init-script