scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: [
        'host.docker.internal:80',
      ]
        labels:
          service: 'my-app'
          group: 'hw5'
          name: 'my-app'

